
baseURL = "https://fbom.club"
languageCode = "en-us"
title = "FBOM International"
theme = "bare"
enableGitInfo = true

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["posts"]
author = "Fine Business Old Man International"
email = "admins@fbom.club"
repoLink = "https://github.com/n3bbq/fbom_website"
description = "Home of Reddit's first on-air ham club"
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
hero_colour = "light"

[[params.social]]
icon = "github"
url = "https://github.com/n3bbq/fbom_website"
